---
# tasks file for ansible-role-redhat-repo

- name: Install extra packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ redhat_repo_extra_packages }}"
  when: ansible_os_family == 'RedHat'

- name: Install repositories
  yum_repository:
    name: "{{ item.key }}"
    description: "{% if 'description' in item.value %}{{ item.value.description }}{% else %}{{ item.key }} repository{% endif %}"
    params: "{{ item.value }}"
  with_dict: "{{ redhat_repo }}"
  register: register_yum_command
  retries: 3
  delay: 10
  until: "'failed' not in register_yum_command"
  when: ansible_os_family == 'RedHat'
